"""Test the gkm kernel against gkmsvm reference outputs.

The reference files in ``tests/data/gkmsvm_reference/`` were generated by
running the original ``gkmsvm`` binary on the 6 standard test sequences
across parameter combinations. Each file is a 6x6 lower-triangular
matrix of kernel values (tab-separated).
"""

import os
import sys
import numpy as np
import pytest

HERE = os.path.dirname(os.path.abspath(__file__))
REF_DIR = os.path.join(HERE, "data", "gkmsvm_reference")

# The 6 standard sequences used by the gkmsvm reference outputs.
SEQS_6 = [
    "ACGTACGTACGTACGTACGT",
    "TTTTAAAAGGGGCCCCAAAA",
    "ACGTTGCATGCATGCATGCA",
    "CCCCGGGGTTTTAAAACCCC",
    "ATATGCGCATATGCGCATAT",
    "GAATTCGAATTCGAATTCGA",
]


def _load_ref_matrix(L, k, d):
    """Load a gkmsvm reference matrix and symmetrize it."""
    path = os.path.join(REF_DIR, f"gkm_L{L}_k{k}_d{d}.txt")
    if not os.path.exists(path):
        pytest.skip(f"reference output not found: {path}")
    rows = []
    with open(path) as f:
        for line in f:
            line = line.strip().rstrip("\t")
            if not line:
                continue
            rows.append([float(x) for x in line.split("\t")])
    n = len(rows)
    M = np.zeros((n, n), dtype=np.float64)
    for i, r in enumerate(rows):
        for j, v in enumerate(r):
            M[i, j] = v
            if i != j:
                M[j, i] = v
    return M


# All (L, k, d) combinations for which we have reference outputs.
PARAM_COMBOS = [
    (6, 4, 1), (6, 4, 2),
    (8, 4, 1), (8, 4, 2), (8, 4, 3),
    (8, 6, 1), (8, 6, 2),
    (10, 4, 1), (10, 4, 2), (10, 4, 3),
    (10, 6, 1), (10, 6, 2), (10, 6, 3),
]


@pytest.mark.parametrize("L,k,d", PARAM_COMBOS)
def test_gkm_matches_gkmsvm_reference(L, k, d):
    """Cross-check our C kernel against the original gkmsvm binary output.

    The gkmsvm binary uses kernel_type="full" with use_rc=True. We expect
    bit-for-bit agreement to within floating-point round-off.
    """
    from kmer.kernels import GKMKernel

    M_ref = _load_ref_matrix(L, k, d)
    kern = GKMKernel(L=L, k=k, d=d, kernel_type="full", use_rc=True)
    kern.set_references(SEQS_6)
    K = np.asarray(kern.kernel())
    assert K.shape == M_ref.shape
    # The algorithm is deterministic; differences come only from float
    # accumulation order between our C implementation and the original
    # gkmsvm binary. 1e-6 is well within that range while still catching
    # algorithmic regressions.
    max_diff = float(np.abs(K - M_ref).max())
    assert max_diff < 1e-6, (
        f"L={L} k={k} d={d}: max diff = {max_diff}\n"
        f"  ref[0,0] = {M_ref[0,0]}, K[0,0] = {K[0,0]}\n"
        f"  ref[0,1] = {M_ref[0,1]}, K[0,1] = {K[0,1]}"
    )


def test_gkm_self_kernel_symmetric():
    """The self-kernel matrix must be symmetric."""
    from kmer.kernels import GKMKernel

    kern = GKMKernel(L=10, k=6, d=3, kernel_type="truncated", use_rc=True)
    kern.set_references(SEQS_6)
    K = np.asarray(kern.kernel())
    assert np.allclose(K, K.T), "self-kernel not symmetric"


def test_gkm_self_kernel_positive_diagonal():
    """Diagonal entries of the self-kernel must be positive."""
    from kmer.kernels import GKMKernel

    kern = GKMKernel(L=10, k=6, d=3, kernel_type="truncated", use_rc=True)
    kern.set_references(SEQS_6)
    K = np.asarray(kern.kernel())
    assert np.all(np.diag(K) > 0), "diagonal not positive"


def test_gkm_self_kernel_unity_diagonal():
    """With the default 'full' kernel_type and use_rc=True, the diagonal
    of the normalized self-kernel should be exactly 1.0 (or 0.0 for
    self-similarity = 1.0). The gkmsvm convention is K[i,i] = 1.0."""
    from kmer.kernels import GKMKernel

    kern = GKMKernel(L=10, k=6, d=3, kernel_type="full", use_rc=True)
    kern.set_references(SEQS_6)
    K = np.asarray(kern.kernel())
    assert np.allclose(np.diag(K), 1.0), (
        f"diagonal not unity: {np.diag(K)}"
    )


def test_gkm_bytes_input():
    """The kernel should accept bytes sequences interchangeably with str."""
    from kmer.kernels import GKMKernel

    seqs_str = ["ACGTACGTACGTACGTACGT", "TTTTAAAAGGGGCCCCAAAA"]
    seqs_bytes = [s.encode("ascii") for s in seqs_str]

    kern_str = GKMKernel(L=10, k=6, d=3, kernel_type="truncated", use_rc=True)
    kern_str.set_references(seqs_str)
    K_str = np.asarray(kern_str.kernel())

    kern_bytes = GKMKernel(L=10, k=6, d=3, kernel_type="truncated", use_rc=True)
    kern_bytes.set_references(seqs_bytes)
    K_bytes = np.asarray(kern_bytes.kernel())

    assert np.allclose(K_str, K_bytes), "str and bytes inputs give different kernels"


def test_gkm_mixed_str_bytes_input():
    """The kernel should accept a mix of str and bytes in the same list."""
    from kmer.kernels import GKMKernel

    seqs_mixed = ["ACGTACGTACGTACGTACGT", b"TTTTAAAAGGGGCCCCAAAA"]
    kern = GKMKernel(L=10, k=6, d=3, kernel_type="truncated", use_rc=True)
    kern.set_references(seqs_mixed)
    K = np.asarray(kern.kernel())
    assert K.shape == (2, 2)


def test_gkm_cross_kernel_shape():
    """Cross-kernel shape is (n_query, n_ref)."""
    from kmer.kernels import GKMKernel

    refs = SEQS_6[:4]
    queries = SEQS_6[4:]
    kern = GKMKernel(L=10, k=6, d=3, kernel_type="truncated", use_rc=True)
    kern.set_references(refs)
    K = np.asarray(kern.kernel(X_query=queries))
    assert K.shape == (len(queries), len(refs))


def test_gkm_sliding_window_scan():
    """Sliding window scan produces one (n_windows, n_ref) array per query."""
    from kmer.kernels import GKMKernel

    kern = GKMKernel(L=10, k=6, d=3, kernel_type="truncated", use_rc=True)
    kern.set_references(SEQS_6)
    long_seq = "ACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGT"
    W = kern.sliding_window_query_kernel([long_seq], window=20, shift=10)
    assert isinstance(W, list)
    assert len(W) == 1
    assert W[0].shape[1] == 6  # n_ref
    assert W[0].shape[0] >= 2  # at least 2 windows


def test_wgkm_kernel_basic():
    """Weighted gkm kernel produces a symmetric matrix."""
    from kmer.kernels import WGKMKernel

    kern = WGKMKernel(
        L=10, k=6, d=3, kernel_type="truncated", use_rc=True,
        weight_kernel="gaussian", weight_sigma=10.0,
    )
    kern.set_references(SEQS_6)
    K = np.asarray(kern.kernel())
    assert K.shape == (6, 6)
    assert np.allclose(K, K.T)


def test_windowed_gkm_kernel_basic():
    """Windowed kernel produces a 3D tensor (n_windows, n, n)."""
    from kmer.kernels import WindowedGKMKernel

    seqs = [
        "ACGTACGTACGTACGTACGTAC",
        "TTTTAAAAGGGGCCCCAAAATT",
        "ACGTTGCATGCATGCATGCATG",
        "CCCCGGGGTTTTAAAACCCCAG",
    ]
    kern = WindowedGKMKernel(L=6, k=4, d=2, window=12, shift=4, padding=0)
    kern.set_references(seqs)
    T = np.asarray(kern.kernel())
    assert T.ndim == 3
    assert T.shape[1] == 4
    assert T.shape[2] == 4
    assert T.shape[0] >= 1


# ======================================================================
# Window overhang tests
# ======================================================================

def test_windowed_kernel_no_right_overhang():
    """Windows must not overhang past pad_right on the right side."""
    from kmer.kernels import WindowedGKMKernel
    import numpy as np

    seqs = [
        "ACGTACGTACGTACGTACGTAC",
        "TTTTAAAAGGGGCCCCAAAATT",
        "ACGTTGCATGCATGCATGCATG",
    ]
    seqlen = len(seqs[0])

    kern = WindowedGKMKernel(L=6, k=4, d=2, window=12, shift=4, padding=0)
    kern.set_references(seqs)
    T = np.asarray(kern.kernel())
    n_windows = T.shape[0]

    # Last window end = (n_windows-1)*shift + window
    last_end = (n_windows - 1) * 4 + 12
    assert last_end <= seqlen, (
        f"Window overhangs: last_end={last_end}, seqlen={seqlen}, n_windows={n_windows}"
    )


def test_windowed_kernel_with_pad_right():
    """With pad_right=2, windows can overhang by at most 2."""
    from kmer.kernels import WindowedGKMKernel
    import numpy as np

    seqs = [
        "ACGTACGTACGTACGTACGTAC",
        "TTTTAAAAGGGGCCCCAAAATT",
        "ACGTTGCATGCATGCATGCATG",
    ]
    seqlen = len(seqs[0])
    pad_right = 2

    kern = WindowedGKMKernel(L=6, k=4, d=2, window=12, shift=4, padding=(0, pad_right))
    kern.set_references(seqs)
    T = np.asarray(kern.kernel())
    n_windows = T.shape[0]

    last_end = (n_windows - 1) * 4 + 12
    overhang = last_end - seqlen
    assert overhang <= pad_right, (
        f"Window overhangs past pad_right: overhang={overhang}, pad_right={pad_right}, "
        f"last_end={last_end}, seqlen={seqlen}, n_windows={n_windows}"
    )


def test_sliding_window_no_right_overhang():
    """Sliding window query should also not overhang past pad_right."""
    from kmer.kernels import GKMKernel
    import numpy as np

    kern = GKMKernel(L=6, k=4, d=2, kernel_type="truncated", use_rc=True)
    kern.set_references(SEQS_6)

    long_seq = "ACGTACGTACGTACGTACGTACGTACGTACGTACGTACGT"  # 40 nt
    seqlen = len(long_seq)

    W = kern.sliding_window_query_kernel([long_seq], window=10, shift=5, padding=0)
    n_windows = W[0].shape[0]
    last_end = (n_windows - 1) * 5 + 10
    assert last_end <= seqlen, (
        f"Sliding window overhangs: last_end={last_end}, seqlen={seqlen}, "
        f"n_windows={n_windows}"
    )
