"""kmer.models.differential — differential k-mer log-odds scorer.

A thin wrapper around sklearn's MultinomialNB that adds:
  1. Auto-generation of negatives via a Shuffler or Chunker background.
  2. Convenience attribute ``kmer_scores_`` (per-k-mer log-odds).
  3. Sklearn-compatible ``decision_function`` returning log-odds sum.

This is statistically Multinomial Naive Bayes with Dirichlet(α)
smoothing and uniform class prior. See sklearn.naive_bayes.MultinomialNB
for the underlying implementation.
"""

from __future__ import annotations

from typing import Optional, Union, Callable

import numpy as np
import pandas as pd
import scipy.sparse as sp
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.naive_bayes import MultinomialNB

from ..perturb import BaseBackgroundModel, KmerShuffler, Chunker
from ..encoders import SpectrumEncoder

# Type alias: background can be a BaseBackgroundModel (Shuffler, Chunker,
# or any custom subclass) or any callable that takes a single sequence
# and returns a shuffled/disrupted version.
Background = Union[BaseBackgroundModel, Callable[[Union[str, bytes]], Union[str, bytes]]]


class DifferentialKmerScorer(BaseEstimator, ClassifierMixin):
    """Differential k-mer log-odds scorer (Multinomial Naive Bayes).

    For each k-mer, computes ``log(p_+,u / p_-,u)`` where ``p_c,u`` is
    the frequency of k-mer ``u`` in class ``c`` with Laplace smoothing.
    To score a new sequence, sums the log-odds of its k-mers.

    Parameters
    ----------
    featurizer : object
        Encoder with ``fit_transform(seqs)`` and ``transform(seqs)`` methods
        returning a scipy.sparse matrix, plus a ``get_feature_names_out()``
        method. Typically :class:`kmer.encoders.SpectrumEncoder` or
        :class:`kmer.encoders.GappyEncoder`.
    background : Shuffler, Chunker, callable, or None
        If ``negatives`` is None in :meth:`fit`, negatives are generated
        by calling ``background.shuffle(seq)`` for each positive (if
        background is a Shuffler/Chunker) or ``background(seq)``
        (if background is a callable). If None, ``fit`` requires
        ``negatives`` to be passed explicitly.
    alpha : float, default 1.0
        Laplace smoothing pseudocount for the positive class.
    beta : float or None, default None
        Laplace smoothing pseudocount for the negative class. If None,
        defaults to ``alpha`` (symmetric smoothing).

    Attributes
    ----------
    kmer_scores_ : pd.Series
        Log-odds score per k-mer (index = feature name from featurizer).
        Positive score = enriched in positives; negative = depleted.
    classes_ : np.ndarray
        Array of class labels, ``[0, 1]``.
    n_positives_ : int
    n_negatives_ : int

    Examples
    --------
    >>> from kmer.models import DifferentialKmerScorer
    >>> from kmer.encoders import SpectrumEncoder
    >>> from kmer.perturb import KmerShuffler
    >>> scorer = DifferentialKmerScorer(
    ...     featurizer=SpectrumEncoder(k=4),
    ...     background=KmerShuffler(k=2, seed=42),
    ... )
    >>> scorer.fit(positives=["ACGTACGTACGT"] * 10)
    >>> scores = scorer.decision_function(["ACGTACGTACGT", "TTTTAAAATTTT"])
    >>> top_motifs = scorer.kmer_scores_.sort_values(ascending=False).head(10)
    """

    def __init__(
        self,
        featurizer,
        background: Optional[Background] = None,
        alpha: float = 1.0,
        beta: Optional[float] = None,
    ):
        self.featurizer = featurizer
        self.background = background
        self.alpha = alpha
        self.beta = beta

    def _generate_negatives(self, positives):
        """Generate one negative per positive using the background."""
        if self.background is None:
            raise ValueError(
                "either pass negatives to fit() or set background="
            )
        if isinstance(self.background, BaseBackgroundModel):
            # Use the unified perturb_many interface — works for
            # KmerShuffler, Chunker, and any custom BaseBackgroundModel
            # subclass. The C-backed ones use their native batch API.
            return self.background.perturb_many(positives)
        # Generic callable.
        return [self.background(s) for s in positives]

    def fit(self, positives, negatives=None):
        """Fit the scorer from positive and (optionally) negative sequences.

        Parameters
        ----------
        positives : list of str or bytes
            Positive-class sequences.
        negatives : list of str or bytes or None
            Negative-class sequences. If None, generated by ``background``.

        Returns
        -------
        self
        """
        if negatives is None:
            negatives = self._generate_negatives(positives)

        # Featurize both classes.
        X_pos = self.featurizer.fit_transform(positives)
        X_neg = self.featurizer.transform(negatives)
        n_pos, n_feat = X_pos.shape
        n_neg, _ = X_neg.shape
        self.n_positives_ = n_pos
        self.n_negatives_ = n_neg

        beta = self.beta if self.beta is not None else self.alpha

        # Compute per-class k-mer frequencies with Laplace smoothing.
        # X_pos and X_neg are CSR; column sums give the count vectors.
        pos_counts = np.asarray(X_pos.sum(axis=0)).ravel() + self.alpha
        neg_counts = np.asarray(X_neg.sum(axis=0)).ravel() + beta
        pos_total = pos_counts.sum()
        neg_total = neg_counts.sum()
        pos_freq = pos_counts / pos_total
        neg_freq = neg_counts / neg_total

        # Log-odds per k-mer. Using natural log here (consistent with
        # sklearn MultinomialNB which uses natural log).
        with np.errstate(divide="ignore", invalid="ignore"):
            log_odds = np.log(pos_freq) - np.log(neg_freq)
        log_odds = np.nan_to_num(log_odds, nan=0.0, posinf=0.0, neginf=0.0)

        self.kmer_scores_ = pd.Series(
            log_odds,
            index=self.featurizer.get_feature_names_out(),
        )
        # Also keep as ndarray for fast scoring.
        self._log_odds_ = log_odds.astype(np.float64)
        self.classes_ = np.array([0, 1])
        return self

    def decision_function(self, seqs):
        """Log-odds score for each sequence.

        Parameters
        ----------
        seqs : list of str or bytes

        Returns
        -------
        np.ndarray
            Shape (n_seqs,). Positive = enriched in positives.
        """
        X = self.featurizer.transform(seqs)
        return np.asarray(X @ self._log_odds_).ravel()

    def predict(self, seqs):
        """Predict class labels (1 if score > 0, else 0)."""
        return (self.decision_function(seqs) > 0).astype(int)

    def predict_proba(self, seqs):
        """Class probabilities via sigmoid of the log-odds score.

        Returns
        -------
        np.ndarray
            Shape (n_seqs, 2). Columns are [P(class=0), P(class=1)].
        """
        score = self.decision_function(seqs)
        p1 = 1.0 / (1.0 + np.exp(-score))
        return np.column_stack([1.0 - p1, p1])

    def fit_predict(self, positives, negatives=None):
        """Convenience: fit then score the positives."""
        self.fit(positives, negatives)
        return self.decision_function(positives)
